"""
PDF Report Generator for AI Compliance Copilot.
"""

from datetime import datetime
from pathlib import Path
from typing import Any

from fpdf import FPDF

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"


class ComplianceReport(FPDF):
    """Custom PDF layout for compliance reports."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "AI Compliance Copilot - Evaluation Report", ln=True, align="C")
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def generate_report(analysis: dict[str, Any]) -> str:
    """
    Generate a PDF report from analysis results.
    Returns the file path of the generated PDF.
    """
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    fw = analysis.get("framework", "unknown")
    filename = f"compliance_report_{fw}_{timestamp}.pdf"
    filepath = REPORTS_DIR / filename

    pdf = ComplianceReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Framework and date
    pdf.set_font("Helvetica", "", 10)
    fw_name = analysis.get("framework_name", fw.upper())
    pdf.cell(0, 8, f"Framework: {fw_name}", ln=True)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.ln(4)

    # Summary
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, analysis.get("summary", "N/A"))
    pdf.ln(4)

    # Risk score
    risk_score = analysis.get("risk_score", 0)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, f"Overall Risk Score: {risk_score}", ln=True)
    pdf.ln(2)

    # Risk breakdown
    risk_summary = analysis.get("risk_summary", {})
    if risk_summary:
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, f"Total Controls: {risk_summary.get('total_controls', 0)}", ln=True)
        pdf.cell(0, 6, f"Compliant: {risk_summary.get('compliant', 0)}", ln=True)
        pdf.cell(0, 6, f"Partial: {risk_summary.get('partial', 0)}", ln=True)
        pdf.cell(0, 6, f"Non-Compliant: {risk_summary.get('non_compliant', 0)}", ln=True)
        pdf.ln(4)

    if analysis.get("human_review_recommended"):
        pdf.set_font("Helvetica", "BI", 10)
        pdf.cell(0, 8, "** Human review recommended for this analysis **", ln=True)
        pdf.ln(2)

    # Compliance results table
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Compliance Results", ln=True)
    pdf.set_font("Helvetica", "B", 9)

    col_widths = [24, 38, 16, 112]
    headers = ["ID", "Title", "Status", "Explanation"]
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 7, h, border=1)
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    for r in analysis.get("compliance_results", []):
        pdf.cell(col_widths[0], 6, r.get("control_id", ""), border=1)
        pdf.cell(col_widths[1], 6, r.get("control_title", "")[:24], border=1)
        pdf.cell(col_widths[2], 6, r.get("status", ""), border=1)
        expl = r.get("explanation", "")
        expl = expl[:68] + "..." if len(expl) > 68 else expl
        pdf.cell(col_widths[3], 6, expl, border=1)
        pdf.ln()

    pdf.ln(6)

    # Recommendations
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Top Recommendations", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for i, rec in enumerate(analysis.get("recommendations", []), 1):
        pdf.multi_cell(0, 6, f"{i}. {rec}")
        pdf.ln(2)

    # Metadata
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 6, f"Generated by AI Compliance Copilot v2.0", ln=True)

    pdf.output(str(filepath))
    return str(filepath)
